"""TODO, system"""


import bpy

import mesh_mesh_align_plus.advanced_tools as maplus_adv_tools
import mesh_mesh_align_plus.align_points as maplus_apt
import mesh_mesh_align_plus.align_lines as maplus_aln
import mesh_mesh_align_plus.align_objects as maplus_aobjects
import mesh_mesh_align_plus.align_planes as maplus_apl
import mesh_mesh_align_plus.axis_rotate as maplus_axr
import mesh_mesh_align_plus.calculate_compose as maplus_calc_compose
import mesh_mesh_align_plus.directional_slide as maplus_ds
import mesh_mesh_align_plus.scale_match_edge as maplus_sme
import mesh_mesh_align_plus.utils.geom as maplus_geom
import mesh_mesh_align_plus.utils.gui_tools as maplus_guitools
import mesh_mesh_align_plus.utils.storage as maplus_storage


classes = (

    maplus_apt.AlignPointsBase,
    maplus_apt.AlignPointsObject,
    maplus_apt.QuickAlignPointsObject,
    maplus_apt.AlignPointsMeshSelected,
    maplus_apt.QuickAlignPointsMeshSelected,
    maplus_apt.AlignPointsWholeMesh,
    maplus_apt.QuickAlignPointsWholeMesh,

    maplus_aln.AlignLinesBase,
    maplus_aln.AlignLinesObject,
    maplus_aln.QuickAlignLinesObject,
    maplus_aln.AlignLinesMeshSelected,
    maplus_aln.AlignLinesWholeMesh,
    maplus_aln.QuickAlignLinesMeshSelected,
    maplus_aln.QuickAlignLinesWholeMesh,

    maplus_apl.AlignPlanesBase,
    maplus_apl.AlignPlanesObject,
    maplus_apl.QuickAlignPlanesObject,
    maplus_apl.AlignPlanesMeshSelected,
    maplus_apl.AlignPlanesWholeMesh,
    maplus_apl.QuickAlignPlanesMeshSelected,
    maplus_apl.QuickAlignPlanesWholeMesh,

    maplus_ds.DirectionalSlideBase,
    maplus_ds.DirectionalSlideObject,
    maplus_ds.QuickDirectionalSlideObject,
    maplus_ds.DirectionalSlideMeshSelected,
    maplus_ds.DirectionalSlideWholeMesh,
    maplus_ds.QuickDirectionalSlideMeshSelected,
    maplus_ds.QuickDirectionalSlideWholeMesh,

    maplus_sme.ScaleMatchEdgeBase,
    maplus_sme.ScaleMatchEdgeObject,
    maplus_sme.QuickScaleMatchEdgeObject,
    maplus_sme.ScaleMatchEdgeMeshSelected,
    maplus_sme.QuickScaleMatchEdgeMeshSelected,
    maplus_sme.ScaleMatchEdgeWholeMesh,
    maplus_sme.QuickScaleMatchEdgeWholeMesh,

    maplus_axr.AxisRotateBase,
    maplus_axr.AxisRotateObject,
    maplus_axr.QuickAxisRotateObject,
    maplus_axr.AxisRotateMeshSelected,
    maplus_axr.AxisRotateWholeMesh,
    maplus_axr.QuickAxisRotateMeshSelected,
    maplus_axr.QuickAxisRotateWholeMesh,

    maplus_aobjects.QuickAlignObjects,

    maplus_calc_compose.CalcLineLengthBase,
    maplus_calc_compose.CalcLineLength,
    maplus_calc_compose.QuickCalcLineLength,
    maplus_calc_compose.CalcRotationalDiffBase,
    maplus_calc_compose.CalcRotationalDiff,
    maplus_calc_compose.QuickCalcRotationalDiff,
    maplus_calc_compose.ComposeNewLineFromOriginBase,
    maplus_calc_compose.ComposeNewLineFromOrigin,
    maplus_calc_compose.QuickComposeNewLineFromOrigin,
    maplus_calc_compose.ComposeNormalFromPlaneBase,
    maplus_calc_compose.ComposeNormalFromPlane,
    maplus_calc_compose.QuickComposeNormalFromPlane,
    maplus_calc_compose.ComposeNewLineFromPointBase,
    maplus_calc_compose.ComposeNewLineFromPoint,
    maplus_calc_compose.QuickComposeNewLineFromPoint,
    maplus_calc_compose.ComposeNewLineAtPointLocationBase,
    maplus_calc_compose.ComposeNewLineAtPointLocation,
    maplus_calc_compose.QuickComposeNewLineAtPointLocation,
    maplus_calc_compose.CalcDistanceBetweenPointsBase,
    maplus_calc_compose.CalcDistanceBetweenPoints,
    maplus_calc_compose.QuickCalcDistanceBetweenPoints,
    maplus_calc_compose.ComposeNewLineFromPointsBase,
    maplus_calc_compose.ComposeNewLineFromPoints,
    maplus_calc_compose.QuickComposeNewLineFromPoints,
    maplus_calc_compose.ComposeNewLineVectorAdditionBase,
    maplus_calc_compose.ComposeNewLineVectorAddition,
    maplus_calc_compose.QuickComposeNewLineVectorAddition,
    maplus_calc_compose.ComposeNewLineVectorSubtractionBase,
    maplus_calc_compose.ComposeNewLineVectorSubtraction,
    maplus_calc_compose.QuickComposeNewLineVectorSubtraction,
    maplus_calc_compose.ComposePointIntersectingLinePlaneBase,
    maplus_calc_compose.ComposePointIntersectingLinePlane,
    maplus_calc_compose.QuickComposePointIntersectingLinePlane,

    maplus_geom.GrabFromGeometryBase,
    maplus_geom.GrabSmeNumeric,
    maplus_geom.GrabAndSetItemKindBase,
    maplus_geom.GrabAverageLocationBase,
    maplus_geom.GrabNormalBase,
    maplus_geom.GrabFromCursorBase,
    maplus_geom.SendCoordToCursorBase,
    maplus_geom.GrabAllSlot1,
    maplus_geom.GrabAllSlot1Loc,
    maplus_geom.GrabAllSlot2,
    maplus_geom.GrabAllSlot2Loc,
    maplus_geom.GrabAllCalcResult,
    maplus_geom.GrabPointFromCursor,
    maplus_geom.Slot1GrabPointFromCursor,
    maplus_geom.Slot2GrabPointFromCursor,
    maplus_geom.CalcResultGrabPointFromCursor,
    maplus_geom.QuickAptSrcGrabPointFromCursor,
    maplus_geom.QuickAptDestGrabPointFromCursor,
    maplus_geom.GrabPointFromActiveLocal,
    maplus_geom.GrabPointFromActiveGlobal,
    maplus_geom.GrabPointSlot1,
    maplus_geom.GrabPointSlot1Loc,
    maplus_geom.GrabPointCalcResult,
    maplus_geom.GrabPointCalcResultLoc,
    maplus_geom.GrabPointSlot2,
    maplus_geom.GrabPointSlot2Loc,
    maplus_geom.PointGrabAvg,
    maplus_geom.LineStartGrabAvg,
    maplus_geom.LineEndGrabAvg,
    maplus_geom.PlaneAGrabAvg,
    maplus_geom.PlaneBGrabAvg,
    maplus_geom.PlaneCGrabAvg,
    maplus_geom.Slot1PointGrabAvg,
    maplus_geom.Slot2PointGrabAvg,
    maplus_geom.CalcResultPointGrabAvg,
    maplus_geom.QuickAptGrabAvgSrc,
    maplus_geom.QuickAptGrabAvgDest,
    maplus_geom.QuickAlignPointsGrabSrc,
    maplus_geom.QuickAlignPointsGrabDest,
    maplus_geom.QuickAlignPointsGrabSrcLoc,
    maplus_geom.QuickAlignPointsGrabDestLoc,
    maplus_geom.SendPointToCursor,
    maplus_geom.Slot1SendPointToCursor,
    maplus_geom.Slot2SendPointToCursor,
    maplus_geom.CalcResultSendPointToCursor,
    maplus_geom.QuickAptSrcSendPointToCursor,
    maplus_geom.QuickAptDestSendPointToCursor,
    maplus_geom.GrabLineStartFromCursor,
    maplus_geom.Slot1GrabLineStartFromCursor,
    maplus_geom.Slot1GrabLineEndFromCursor,
    maplus_geom.Slot2GrabLineStartFromCursor,
    maplus_geom.Slot2GrabLineEndFromCursor,
    maplus_geom.CalcResultGrabLineStartFromCursor,
    maplus_geom.CalcResultGrabLineEndFromCursor,
    maplus_geom.QuickAlnSrcGrabLineStartFromCursor,
    maplus_geom.QuickAlnDestGrabLineStartFromCursor,
    maplus_geom.QuickAxrSrcGrabLineStartFromCursor,
    maplus_geom.QuickDsSrcGrabLineStartFromCursor,
    maplus_geom.QuickDsDestGrabLineStartFromCursor,
    maplus_geom.QuickSmeSrcGrabLineStartFromCursor,
    maplus_geom.QuickSmeDestGrabLineStartFromCursor,
    maplus_geom.GrabLineStartFromActiveLocal,
    maplus_geom.GrabLineStartFromActiveGlobal,
    maplus_geom.Slot1GrabLineEndFromActiveLocal,
    maplus_geom.Slot2GrabLineEndFromActiveLocal,
    maplus_geom.CalcResultGrabLineEndFromActiveLocal,
    maplus_geom.Slot1GrabLineEndFromActiveGlobal,
    maplus_geom.Slot2GrabLineEndFromActiveGlobal,
    maplus_geom.CalcResultGrabLineEndFromActiveGlobal,
    maplus_geom.Slot1GrabLineStartFromActiveLocal,
    maplus_geom.Slot1GrabLineStartFromActiveGlobal,
    maplus_geom.Slot2GrabLineStartFromActiveLocal,
    maplus_geom.Slot2GrabLineStartFromActiveGlobal,
    maplus_geom.CalcResultGrabLineStartFromActiveLocal,
    maplus_geom.CalcResultGrabLineStartFromActiveGlobal,
    maplus_geom.Slot1GrabAvgLineStart,
    maplus_geom.Slot2GrabAvgLineStart,
    maplus_geom.CalcResultGrabAvgLineStart,
    maplus_geom.Slot1GrabAvgLineEnd,
    maplus_geom.Slot2GrabAvgLineEnd,
    maplus_geom.CalcResultGrabAvgLineEnd,
    maplus_geom.QuickAlnGrabAvgSrcLineStart,
    maplus_geom.QuickAlnGrabAvgDestLineStart,
    maplus_geom.QuickAlnGrabAvgSrcLineEnd,
    maplus_geom.QuickAlnGrabAvgDestLineEnd,
    maplus_geom.QuickAxrGrabAvgSrcLineStart,
    maplus_geom.QuickAxrGrabAvgSrcLineEnd,
    maplus_geom.QuickDsGrabAvgSrcLineStart,
    maplus_geom.QuickDsGrabAvgSrcLineEnd,
    maplus_geom.QuickSmeGrabAvgSrcLineStart,
    maplus_geom.QuickSmeGrabAvgDestLineStart,
    maplus_geom.QuickSmeGrabAvgSrcLineEnd,
    maplus_geom.QuickSmeGrabAvgDestLineEnd,
    maplus_geom.QuickAlnSrcGrabLineStartFromActiveLocal,
    maplus_geom.QuickAlnSrcGrabLineStartFromActiveGlobal,
    maplus_geom.QuickAlnDestGrabLineStartFromActiveLocal,
    maplus_geom.QuickAlnDestGrabLineStartFromActiveGlobal,
    maplus_geom.QuickAxrSrcGrabLineStartFromActiveLocal,
    maplus_geom.QuickAxrSrcGrabLineStartFromActiveGlobal,
    maplus_geom.QuickDsSrcGrabLineStartFromActiveLocal,
    maplus_geom.QuickDsSrcGrabLineStartFromActiveGlobal,
    maplus_geom.QuickDsDestGrabLineStartFromActiveLocal,
    maplus_geom.QuickDsDestGrabLineStartFromActiveGlobal,
    maplus_geom.QuickSmeSrcGrabLineStartFromActiveLocal,
    maplus_geom.QuickSmeSrcGrabLineStartFromActiveGlobal,
    maplus_geom.QuickSmeDestGrabLineStartFromActiveLocal,
    maplus_geom.QuickSmeDestGrabLineStartFromActiveGlobal,
    maplus_geom.SendLineStartToCursor,
    maplus_geom.Slot1SendLineStartToCursor,
    maplus_geom.Slot1SendLineEndToCursor,
    maplus_geom.Slot2SendLineStartToCursor,
    maplus_geom.Slot2SendLineEndToCursor,
    maplus_geom.CalcResultSendLineStartToCursor,
    maplus_geom.CalcResultSendLineEndToCursor,
    maplus_geom.QuickAlnSrcSendLineStartToCursor,
    maplus_geom.QuickAlnDestSendLineStartToCursor,
    maplus_geom.QuickAxrSrcSendLineStartToCursor,
    maplus_geom.QuickDsSrcSendLineStartToCursor,
    maplus_geom.QuickDsDestSendLineStartToCursor,
    maplus_geom.QuickSmeSrcSendLineStartToCursor,
    maplus_geom.QuickSmeDestSendLineStartToCursor,
    maplus_geom.GrabLineEndFromCursor,
    maplus_geom.QuickAlnSrcGrabLineEndFromCursor,
    maplus_geom.QuickAlnDestGrabLineEndFromCursor,
    maplus_geom.QuickAxrSrcGrabLineEndFromCursor,
    maplus_geom.QuickDsSrcGrabLineEndFromCursor,
    maplus_geom.QuickDsDestGrabLineEndFromCursor,
    maplus_geom.QuickSmeSrcGrabLineEndFromCursor,
    maplus_geom.QuickSmeDestGrabLineEndFromCursor,
    maplus_geom.GrabLineEndFromActiveLocal,
    maplus_geom.GrabLineEndFromActiveGlobal,
    maplus_geom.QuickAlnSrcGrabLineEndFromActiveLocal,
    maplus_geom.QuickAlnSrcGrabLineEndFromActiveGlobal,
    maplus_geom.QuickAlnDestGrabLineEndFromActiveLocal,
    maplus_geom.QuickAlnDestGrabLineEndFromActiveGlobal,
    maplus_geom.QuickAxrSrcGrabLineEndFromActiveGlobal,
    maplus_geom.QuickAxrSrcGrabLineEndFromActiveLocal,
    maplus_geom.QuickDsSrcGrabLineEndFromActiveLocal,
    maplus_geom.QuickDsSrcGrabLineEndFromActiveGlobal,
    maplus_geom.QuickDsDestGrabLineEndFromActiveLocal,
    maplus_geom.QuickDsDestGrabLineEndFromActiveGlobal,
    maplus_geom.QuickSmeSrcGrabLineEndFromActiveLocal,
    maplus_geom.QuickSmeSrcGrabLineEndFromActiveGlobal,
    maplus_geom.QuickSmeDestGrabLineEndFromActiveLocal,
    maplus_geom.QuickSmeDestGrabLineEndFromActiveGlobal,
    maplus_geom.SendLineEndToCursor,
    maplus_geom.QuickAlnSrcSendLineEndToCursor,
    maplus_geom.QuickAlnDestSendLineEndToCursor,
    maplus_geom.QuickAxrSrcSendLineEndToCursor,
    maplus_geom.QuickDsSrcSendLineEndToCursor,
    maplus_geom.QuickDsDestSendLineEndToCursor,
    maplus_geom.QuickSmeSrcSendLineEndToCursor,
    maplus_geom.QuickSmeDestSendLineEndToCursor,
    maplus_geom.GrabAllVertsLineLocal,
    maplus_geom.GrabAllVertsLineGlobal,
    maplus_geom.GrabLineSlot1,
    maplus_geom.GrabLineSlot1Loc,
    maplus_geom.GrabLineSlot2,
    maplus_geom.GrabLineSlot2Loc,
    maplus_geom.GrabLineCalcResult,
    maplus_geom.GrabLineCalcResultLoc,
    maplus_geom.GrabNormal,
    maplus_geom.Slot1GrabNormal,
    maplus_geom.Slot2GrabNormal,
    maplus_geom.CalcResultGrabNormal,
    maplus_geom.QuickAlnGrabNormalSrc,
    maplus_geom.QuickAlnGrabNormalDest,
    maplus_geom.QuickAxrGrabNormalSrc,
    maplus_geom.QuickDsGrabNormalSrc,
    maplus_geom.QuickSmeGrabNormalSrc,
    maplus_geom.QuickSmeGrabNormalDest,
    maplus_geom.QuickAlignLinesGrabSrc,
    maplus_geom.QuickAlignLinesGrabSrcLoc,
    maplus_geom.QuickAlignLinesGrabDest,
    maplus_geom.QuickAlignLinesGrabDestLoc,
    maplus_geom.QuickScaleMatchEdgeGrabSrc,
    maplus_geom.QuickScaleMatchEdgeGrabSrcLoc,
    maplus_geom.QuickScaleMatchEdgeGrabDest,
    maplus_geom.QuickScaleMatchEdgeGrabDestLoc,
    maplus_geom.QuickAxisRotateGrabSrc,
    maplus_geom.QuickAxisRotateGrabSrcLoc,
    maplus_geom.QuickDirectionalSlideGrabSrc,
    maplus_geom.QuickDirectionalSlideGrabSrcLoc,
    maplus_geom.GrabPlaneAFromCursor,
    maplus_geom.Slot1GrabPlaneAFromCursor,
    maplus_geom.Slot1GrabPlaneBFromCursor,
    maplus_geom.Slot1GrabPlaneCFromCursor,
    maplus_geom.Slot2GrabPlaneAFromCursor,
    maplus_geom.Slot2GrabPlaneBFromCursor,
    maplus_geom.Slot2GrabPlaneCFromCursor,
    maplus_geom.CalcResultGrabPlaneAFromCursor,
    maplus_geom.CalcResultGrabPlaneBFromCursor,
    maplus_geom.CalcResultGrabPlaneCFromCursor,
    maplus_geom.QuickAplSrcGrabPlaneAFromCursor,
    maplus_geom.QuickAplDestGrabPlaneAFromCursor,
    maplus_geom.GrabPlaneAFromActiveLocal,
    maplus_geom.GrabPlaneAFromActiveGlobal,
    maplus_geom.Slot1GrabPlaneAFromActiveLocal,
    maplus_geom.Slot1GrabPlaneAFromActiveGlobal,
    maplus_geom.Slot1GrabPlaneBFromActiveLocal,
    maplus_geom.Slot1GrabPlaneBFromActiveGlobal,
    maplus_geom.Slot1GrabPlaneCFromActiveLocal,
    maplus_geom.Slot1GrabPlaneCFromActiveGlobal,
    maplus_geom.Slot2GrabPlaneAFromActiveLocal,
    maplus_geom.Slot2GrabPlaneAFromActiveGlobal,
    maplus_geom.Slot2GrabPlaneBFromActiveLocal,
    maplus_geom.Slot2GrabPlaneBFromActiveGlobal,
    maplus_geom.Slot2GrabPlaneCFromActiveLocal,
    maplus_geom.Slot2GrabPlaneCFromActiveGlobal,
    maplus_geom.CalcResultGrabPlaneAFromActiveLocal,
    maplus_geom.CalcResultGrabPlaneAFromActiveGlobal,
    maplus_geom.CalcResultGrabPlaneBFromActiveLocal,
    maplus_geom.CalcResultGrabPlaneBFromActiveGlobal,
    maplus_geom.CalcResultGrabPlaneCFromActiveLocal,
    maplus_geom.CalcResultGrabPlaneCFromActiveGlobal,
    maplus_geom.Slot1GrabAvgPlaneA,
    maplus_geom.Slot1GrabAvgPlaneB,
    maplus_geom.Slot1GrabAvgPlaneC,
    maplus_geom.Slot2GrabAvgPlaneA,
    maplus_geom.Slot2GrabAvgPlaneB,
    maplus_geom.Slot2GrabAvgPlaneC,
    maplus_geom.CalcResultGrabAvgPlaneA,
    maplus_geom.CalcResultGrabAvgPlaneB,
    maplus_geom.CalcResultGrabAvgPlaneC,
    maplus_geom.QuickAplGrabAvgSrcPlaneA,
    maplus_geom.QuickAplGrabAvgDestPlaneA,
    maplus_geom.QuickAplSrcGrabPlaneAFromActiveLocal,
    maplus_geom.QuickAplSrcGrabPlaneAFromActiveGlobal,
    maplus_geom.QuickAplDestGrabPlaneAFromActiveLocal,
    maplus_geom.QuickAplDestGrabPlaneAFromActiveGlobal,
    maplus_geom.SendPlaneAToCursor,
    maplus_geom.Slot1SendPlaneAToCursor,
    maplus_geom.Slot1SendPlaneBToCursor,
    maplus_geom.Slot1SendPlaneCToCursor,
    maplus_geom.Slot2SendPlaneAToCursor,
    maplus_geom.Slot2SendPlaneBToCursor,
    maplus_geom.Slot2SendPlaneCToCursor,
    maplus_geom.CalcResultSendPlaneAToCursor,
    maplus_geom.CalcResultSendPlaneBToCursor,
    maplus_geom.CalcResultSendPlaneCToCursor,
    maplus_geom.QuickAplSrcSendPlaneAToCursor,
    maplus_geom.QuickAplDestSendPlaneAToCursor,
    maplus_geom.GrabPlaneBFromCursor,
    maplus_geom.QuickAplSrcGrabPlaneBFromCursor,
    maplus_geom.QuickAplDestGrabPlaneBFromCursor,
    maplus_geom.GrabPlaneBFromActiveLocal,
    maplus_geom.GrabPlaneBFromActiveGlobal,
    maplus_geom.QuickAplGrabAvgSrcPlaneB,
    maplus_geom.QuickAplGrabAvgDestPlaneB,
    maplus_geom.QuickAplSrcGrabPlaneBFromActiveLocal,
    maplus_geom.QuickAplSrcGrabPlaneBFromActiveGlobal,
    maplus_geom.QuickAplDestGrabPlaneBFromActiveLocal,
    maplus_geom.QuickAplDestGrabPlaneBFromActiveGlobal,
    maplus_geom.SendPlaneBToCursor,
    maplus_geom.QuickAplSrcSendPlaneBToCursor,
    maplus_geom.QuickAplDestSendPlaneBToCursor,
    maplus_geom.GrabPlaneCFromCursor,
    maplus_geom.QuickAplSrcGrabPlaneCFromCursor,
    maplus_geom.QuickAplDestGrabPlaneCFromCursor,
    maplus_geom.GrabPlaneCFromActiveLocal,
    maplus_geom.GrabPlaneCFromActiveGlobal,
    maplus_geom.QuickAplGrabAvgSrcPlaneC,
    maplus_geom.QuickAplGrabAvgDestPlaneC,
    maplus_geom.QuickAplSrcGrabPlaneCFromActiveLocal,
    maplus_geom.QuickAplSrcGrabPlaneCFromActiveGlobal,
    maplus_geom.QuickAplDestGrabPlaneCFromActiveLocal,
    maplus_geom.QuickAplDestGrabPlaneCFromActiveGlobal,
    maplus_geom.SendPlaneCToCursor,
    maplus_geom.QuickAplSrcSendPlaneCToCursor,
    maplus_geom.QuickAplDestSendPlaneCToCursor,
    maplus_geom.GrabAllVertsPlaneLocal,
    maplus_geom.GrabAllVertsPlaneGlobal,
    maplus_geom.GrabPlaneSlot1Loc,
    maplus_geom.GrabPlaneSlot1,
    maplus_geom.GrabPlaneSlot2Loc,
    maplus_geom.GrabPlaneSlot2,
    maplus_geom.GrabPlaneCalcResultLoc,
    maplus_geom.GrabPlaneCalcResult,
    maplus_geom.QuickAlignPlanesGrabSrc,
    maplus_geom.QuickAlignPlanesGrabDest,
    maplus_geom.QuickAlignPlanesGrabSrcLoc,
    maplus_geom.QuickAlignPlanesGrabDestLoc,
    maplus_geom.SwapPointsBase,
    maplus_geom.SwapLinePoints,
    maplus_geom.Slot1SwapLinePoints,
    maplus_geom.Slot2SwapLinePoints,
    maplus_geom.CalcResultSwapLinePoints,
    maplus_geom.QuickAlnSrcSwapLinePoints,
    maplus_geom.QuickAlnDestSwapLinePoints,
    maplus_geom.QuickAxrSrcSwapLinePoints,
    maplus_geom.QuickDsSrcSwapLinePoints,
    maplus_geom.QuickSmeSrcSwapLinePoints,
    maplus_geom.QuickSmeDestSwapLinePoints,
    maplus_geom.SwapPlaneAPlaneB,
    maplus_geom.SwapPlaneAPlaneC,
    maplus_geom.SwapPlaneBPlaneC,
    maplus_geom.Slot1SwapPlaneAPlaneB,
    maplus_geom.Slot1SwapPlaneAPlaneC,
    maplus_geom.Slot1SwapPlaneBPlaneC,
    maplus_geom.Slot2SwapPlaneAPlaneB,
    maplus_geom.Slot2SwapPlaneAPlaneC,
    maplus_geom.Slot2SwapPlaneBPlaneC,
    maplus_geom.CalcResultSwapPlaneAPlaneB,
    maplus_geom.CalcResultSwapPlaneAPlaneC,
    maplus_geom.CalcResultSwapPlaneBPlaneC,
    maplus_geom.QuickAplSrcSwapPlaneAPlaneB,
    maplus_geom.QuickAplSrcSwapPlaneAPlaneC,
    maplus_geom.QuickAplSrcSwapPlaneBPlaneC,
    maplus_geom.QuickAplDestSwapPlaneAPlaneB,
    maplus_geom.QuickAplDestSwapPlaneAPlaneC,
    maplus_geom.QuickAplDestSwapPlaneBPlaneC,
    maplus_geom.SetOtherComponentsBase,
    maplus_geom.ZeroOtherPointX,
    maplus_geom.ZeroOtherPointY,
    maplus_geom.ZeroOtherPointZ,
    maplus_geom.ZeroOtherLineStartX,
    maplus_geom.ZeroOtherLineStartY,
    maplus_geom.ZeroOtherLineStartZ,
    maplus_geom.ZeroOtherLineEndX,
    maplus_geom.ZeroOtherLineEndY,
    maplus_geom.ZeroOtherLineEndZ,
    maplus_geom.ZeroOtherPlanePointAX,
    maplus_geom.ZeroOtherPlanePointAY,
    maplus_geom.ZeroOtherPlanePointAZ,
    maplus_geom.ZeroOtherPlanePointBX,
    maplus_geom.ZeroOtherPlanePointBY,
    maplus_geom.ZeroOtherPlanePointBZ,
    maplus_geom.ZeroOtherPlanePointCX,
    maplus_geom.ZeroOtherPlanePointCY,
    maplus_geom.ZeroOtherPlanePointCZ,
    maplus_geom.OneOtherPointX,
    maplus_geom.OneOtherPointY,
    maplus_geom.OneOtherPointZ,
    maplus_geom.OneOtherLineStartX,
    maplus_geom.OneOtherLineStartY,
    maplus_geom.OneOtherLineStartZ,
    maplus_geom.OneOtherLineEndX,
    maplus_geom.OneOtherLineEndY,
    maplus_geom.OneOtherLineEndZ,
    maplus_geom.OneOtherPlanePointAX,
    maplus_geom.OneOtherPlanePointAY,
    maplus_geom.OneOtherPlanePointAZ,
    maplus_geom.OneOtherPlanePointBX,
    maplus_geom.OneOtherPlanePointBY,
    maplus_geom.OneOtherPlanePointBZ,
    maplus_geom.OneOtherPlanePointCX,
    maplus_geom.OneOtherPlanePointCY,
    maplus_geom.OneOtherPlanePointCZ,
    maplus_geom.ApplyGeomModifiers,
    maplus_geom.ShowHideQuickGeomBaseClass,
    maplus_geom.ShowHideQuickCalcSlot1Geom,
    maplus_geom.ShowHideQuickCalcSlot2Geom,
    maplus_geom.ShowHideQuickCalcResultGeom,
    maplus_geom.ShowHideQuickAptSrcGeom,
    maplus_geom.ShowHideQuickAptDestGeom,
    maplus_geom.ShowHideQuickAlnSrcGeom,
    maplus_geom.ShowHideQuickAlnDestGeom,
    maplus_geom.ShowHideQuickAplSrcGeom,
    maplus_geom.ShowHideQuickAplDestGeom,
    maplus_geom.ShowHideQuickAxrSrcGeom,
    maplus_geom.ShowHideQuickDsSrcGeom,
    maplus_geom.ShowHideQuickSmeSrcGeom,
    maplus_geom.ShowHideQuickSmeDestGeom,

    maplus_storage.MAPlusPrimitive,
    maplus_storage.MAPlusData,
    maplus_storage.CopyToOtherBase,

    maplus_storage.PasteIntoAdvToolsActive,
    maplus_storage.CopyFromAdvToolsActive,
    maplus_storage.PasteIntoSlot1,
    maplus_storage.CopyFromSlot1,
    maplus_storage.PasteIntoSlot2,
    maplus_storage.CopyFromSlot2,
    maplus_storage.CopyFromCalcResult,
    maplus_storage.PasteIntoCalcResult,
    maplus_storage.PasteIntoAptSrc,
    maplus_storage.CopyFromAptSrc,
    maplus_storage.PasteIntoAptDest,
    maplus_storage.CopyFromAptDest,
    maplus_storage.PasteIntoAlnSrc,
    maplus_storage.CopyFromAlnSrc,
    maplus_storage.PasteIntoAlnDest,
    maplus_storage.CopyFromAlnDest,
    maplus_storage.PasteIntoAplSrc,
    maplus_storage.CopyFromAplSrc,
    maplus_storage.PasteIntoAplDest,
    maplus_storage.CopyFromAplDest,
    maplus_storage.PasteIntoAxrSrc,
    maplus_storage.CopyFromAxrSrc,
    maplus_storage.PasteIntoDsSrc,
    maplus_storage.CopyFromDsSrc,
    maplus_storage.PasteIntoSmeSrc,
    maplus_storage.CopyFromSmeSrc,
    maplus_storage.PasteIntoSmeDest,
    maplus_storage.CopyFromSmeDest,

    maplus_adv_tools.AddListItemBase,
    maplus_adv_tools.AddNewPoint,
    maplus_adv_tools.AddNewLine,
    maplus_adv_tools.AddNewPlane,
    maplus_adv_tools.AddNewCalculation,
    maplus_adv_tools.AddNewTransformation,

    maplus_adv_tools.ChangeTypeBaseClass,
    maplus_adv_tools.ChangeTypeToPointPrim,
    maplus_adv_tools.ChangeTypeToLinePrim,
    maplus_adv_tools.ChangeTypeToPlanePrim,
    maplus_adv_tools.ChangeTypeToCalcPrim,
    maplus_adv_tools.ChangeTypeToTransfPrim,
    maplus_adv_tools.ChangeCalcBaseClass,
    maplus_adv_tools.ChangeCalcToSingle,
    maplus_adv_tools.ChangeCalcToMulti,
    maplus_adv_tools.ChangeTransfBaseClass,
    maplus_adv_tools.ChangeTransfToAlignPoints,
    maplus_adv_tools.ChangeTransfToDirectionalSlide,
    maplus_adv_tools.ChangeTransfToScaleMatchEdge,
    maplus_adv_tools.ChangeTransfToAxisRotate,
    maplus_adv_tools.ChangeTransfToAlignLines,
    maplus_adv_tools.ChangeTransfToAlignPlanes,

    maplus_adv_tools.DuplicateItemBase,
    maplus_adv_tools.RemoveListItem,
    maplus_adv_tools.SpecialsAddFromActiveBase,
    maplus_adv_tools.SpecialsAddPointFromActiveGlobal,
    maplus_adv_tools.SpecialsAddLineFromActiveGlobal,
    maplus_adv_tools.SpecialsAddPlaneFromActiveGlobal,

    # GUI registration
    maplus_adv_tools.MAPlusList,
    maplus_adv_tools.MAPlusGui,

    maplus_apt.QuickAlignPointsGUI,
    maplus_aln.QuickAlignLinesGUI,
    maplus_apl.QuickAlignPlanesGUI,
    maplus_axr.QuickAxisRotateGUI,
    maplus_ds.QuickDirectionalSlideGUI,
    maplus_sme.QuickSMEGUI,
    maplus_aobjects.QuickAlignObjectsGUI,
    maplus_calc_compose.CalculateAndComposeGUI,

    # maplus_except.UniqueNameError,
    # maplus_except.NonMeshGrabError,
    # maplus_exceptInsufficientSelectionError,
)


def register():
    # Make custom classes available inside blender via bpy.types
    for cls in classes:
        bpy.utils.register_class(cls)

    # Extend the scene class here to include the addon data
    bpy.types.Scene.maplus_data = bpy.props.PointerProperty(
        type=maplus_storage.MAPlusData
    )

    bpy.types.VIEW3D_MT_object_specials.append(maplus_guitools.specials_menu_items)
    bpy.types.VIEW3D_MT_edit_mesh_specials.append(maplus_guitools.specials_menu_items)


def unregister():
    del bpy.types.Scene.maplus_data
    bpy.types.VIEW3D_MT_object_specials.remove(maplus_guitools.specials_menu_items)
    bpy.types.VIEW3D_MT_edit_mesh_specials.remove(maplus_guitools.specials_menu_items)

    # Remove custom classes from blender's bpy.types
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)
